### ISSUE TITLE
tsv mode: if multiple prefix contractions are possible, choose the longest namespace

### ISSUE THREAD

**Issue by cmungall** [INCATools/relation-graph#168]
given:

```yaml
UBERON: "http://purl.obolibrary.org/obo/UBERON_"
obo: "http://purl.obolibrary.org/obo/"
```

either emit an error, as the results are non-deterministic, or (preferably) choose the longest namespace, making the shortest CURIE, ie. favor UBERON:nnnn

**Comment by balhoff** [comment]
I'm using a built-in Jena class for this, but now that I look at its docs it says:

>If there are multiple applicable mappings available, the "most recent" is chosen if that is possible, otherwise one is picked "at random".

So I guess I should implement it myself.
