### ISSUE TITLE
add rdfs:labels to output

### ISSUE THREAD

**Issue by wdduncan** [INCATools/relation-graph#249]
I understand some are against this, but adding rdfs:labels to output would be helpful. Since OBO ontologies use opaque IRIs, you have to look up the class names if you don't remember the IRI's label ... which often happens for me :)

FWIW, here is a robot command to extract the labels:
```
robot remove -i input.owl --select annotation-properties --exclude-term rdfs:label \                                                                
      remove --axioms logical \
      -o output-labels.ttl 
```
A sparql query is easy too.

The output would need to be merged with the graph.

cc @balhoff

**Comment by balhoff** [comment]
I think this is outside the scope of relation-graph.
