### ISSUE TITLE
Provide TSV export

### ISSUE THREAD

**Issue by cmungall** [INCATools/relation-graph#25]
4 columns:

 * subject
 * predicate
 * object
 * named graph (e.g redundant, non-redundant)

With CURIEs

Why:

 1. many tools speak TSV (pandas, sqlite, cut, grep)
 2. loading the ttl files using the OWLAPI causes inference that the OPs are actually APs. I believe querying by robot will route through the API causing injection of these unwanted triples
 3. having the two files combined into one is useful

**Comment by cmungall** [comment]
Discussing this on the translator reasoning call.. kgx format may be good

**Comment by balhoff** [comment]
In the near future I would like to stop producing the non-redundant graph, because it is not adequately non-redundant. Instead I will provide SPARQL CONSTRUCT (and possibly Souffle) post-processing instructions. So for the time being it would be cleaner to produce two files. Sound okay?
